# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 22:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField()),
                ('biography', models.TextField()),
                ('logo', models.ImageField(upload_to='/media/images/')),
                ('slogan', models.CharField(max_length=50)),
                ('music', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None)),
            ],
        ),
    ]
