# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.Events'),
        ),
    ]
