# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160907_0143'),
        ('users', '0002_auto_20160907_0214'),
    ]

    operations = [
    ]
